root = "."
tmp_dir = "tmp"

[build]
cmd = "/usr/local/go/bin/go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", ".git", "migrations"]

[log]
time = true