ALTER TABLE meditations ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE gym_visits ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE trips ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE credit_cards ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE sports ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE vehicles ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE transactions ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE user_sessions ALTER COLUMN expires_at TYPE TIMESTAMP USING expires_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE user_profiles ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE gym_visit_exercises ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE gym_exercise_sets ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE notifications ALTER COLUMN read_at TYPE TIMESTAMP USING read_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN dismissed_at TYPE TIMESTAMP USING dismissed_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE vehicle_air_fills ALTER COLUMN filled_at TYPE TIMESTAMP USING filled_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE vehicle_fuel_fillups ALTER COLUMN filled_at TYPE TIMESTAMP USING filled_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE vehicle_fuel_items ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE next_month_purchases ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata', ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE gym_reminder_deliveries ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'Asia/Kolkata';
